Repository 7DevsApps/cognito-sync-service, pull requests merged in 2019-08, with the labels that each got.

#2 Negative specs
  doc/ca_create!.md
  spec/cognito_sync_service_spec.rb
Labels: enhancement

#4 Find by token! feature
  .env.example
  .gitignore
  README.md
  doc/find_by_access_token!.md
  lib/cognito-sync-service.rb
  spec/cognito_sync_service_spec.rb
Labels: enhancement

#7 Add errors output to methods docs
  doc/ca_create!.md
  doc/ca_delete!.md
  doc/ca_disable!.md
  doc/ca_find!.md
  doc/ca_initiate_auth!.md
  doc/ca_respond_to_auth_challenge!.md
  doc/ca_update!.md
  doc/find_by_access_token!.md
Labels: enhancement

#9 Add ca_enable! method
  README.md
  doc/ca_enable!.md
  lib/cognito-sync-service.rb
  spec/cognito_sync_service_spec.rb
Labels: documentation, enhancement

#10 Add #ca_refresh_tokens!
  README.md
  doc/ca_refresh_tokens!.md
  doc/ca_respond_to_auth_challenge!.md
  lib/cognito-sync-service.rb
  spec/cognito_sync_service_spec.rb
Labels: documentation, enhancement

#12 Rename to c_find_by_access_token
  README.md
  doc/c_find_by_access_token!.md
  lib/cognito-sync-service.rb
  spec/cognito_sync_service_spec.rb
Labels: documentation, enhancement

#14 Nokogiri update version
  Gemfile.lock
Labels: invalid

#13 Ca reset user password
  README.md
  doc/ca_set_user_password!.md
  lib/cognito-sync-service.rb
  spec/cognito_sync_service_spec.rb
Labels: documentation, enhancement
